### PR TITLE
tinymce editor has been fixed

### PR DESCRIPTION
**Pull request by uyo-obong**
Screenshot_2019-10-05_15-19-31

### CODE REVIEW

**Comment by sulaimanxyz** [comment]
@uyo-obong, were you able to add the box-shadow to the text editor as recommended?

**Comment by Jamesjay4199** [comment]
@uyo-obong, is this ready to be merged?
I see that you haven't responded to @sulaimanxyz yet?

**Comment by Jamesjay4199** [comment]
Also, merge conflicts needs to be resolved.
It seems some of the work done here were one in #35

**Comment by Jamesjay4199** [comment]
@uyo-obong, after addressing a comment, can you respond `Done` or something similar, so we track what has been done, thanks.

**Pull request merged**
