### PR TITLE
 fixed store name

### PR DESCRIPTION
**Pull request by uyo-obong**
Screenshot_2019-10-11_15-08-53

### CODE REVIEW

**Comment by sulaimanxyz** [comment]
Suspend this, i'll revert first thing tomorrow morning. I have gone through the commits and have concerns.

**Comment by sulaimanxyz** [comment]
@Jamesjay4199 I left a comment 40 minutes ago. There's something wrong with this PR. That's why I said you should suspend the merge.

Please revoke the merging. I'll address it properly tomorrow.
05a79835-9d91-4d3d-b0b8-40bfd6a3fa6c

**Comment by Jamesjay4199** [comment]
Reverted

**Comment by sulaimanxyz** [comment]
@Jamesjay4199 I left a comment 40 minutes ago. There's something wrong with this PR. That's why I said you should suspend the merge.

I asked @uyo-obong to render "Webstore Name"and he rendered "Webstore Title".
Render Webstore Name -2
8d718a1f-1459-455c-9b92-450172af02ed

Please revoke the merging. I'll address it properly tomorrow.

**Comment by sulaimanxyz** [comment]
> Reverted

Thanks.

**Pull request merged**
